services:
  - type: web
    name: flask-image-gallery
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://chennaicorprm:biuIvx7I7akjQx1B@cluster0.5y2ndpd.mongodb.net/VirtualTour?retryWrites=true&w=majority"